### PR TITLE
Remove unused imports and variables

### PR DESCRIPTION
**Pull request by jsf9k**
These unused imports and variables were pointed out by LGTM.

### CODE REVIEW

**Comment by jsf9k** [comment]
Looks like the build is failing because [this link](https://blogs.msdn.microsoft.com/tzink/2015/03/13/how-to-align-with-spf-and-dmarc-for-your-domain-if-you-use-a-lot-of-3rd-parties-to-send-email-as-you/) no longer exists.  :disappointed:

**Comment by jsf9k** [comment]
This pull request **fixes 3 alerts** when merging 9ba4a3b8ea5b4898580dbb3f57492ccd8f0d877d into 1551376733545d22063a705e549425ace65f3bf9 - [view on LGTM.com](https://lgtm.com/projects/g/cisagov/cyber.dhs.gov/rev/pr-98148a93968c6f36fe82490067867861516c6859)

**fixed alerts:**

* 3 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by jsf9k** [comment]
Looks like Mr. Zonk's blog has been removed from Microsoft's site altogether.  I did find [this copy](https://web.archive.org/web/20190120184651/https://blogs.msdn.microsoft.com/tzink/2015/03/13/how-to-align-with-spf-and-dmarc-for-your-domain-if-you-use-a-lot-of-3rd-parties-to-send-email-as-you/) from January 2019 via the Wayback Machine.

Do we want to link there instead?  Find a similar link that is still active?

**Comment by h-m-f-t** [comment]
I'm good with a Wayback Machine link!

**Comment by jsf9k** [comment]
This pull request **fixes 3 alerts** when merging 158fea28ebb72e1546841bc0f0e5b2d93bb93f7e into 1551376733545d22063a705e549425ace65f3bf9 - [view on LGTM.com](https://lgtm.com/projects/g/cisagov/cyber.dhs.gov/rev/pr-74ef4056e29a978d8cc850e9d2a5fa61f81b2e58)

**fixed alerts:**

* 3 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by jsf9k** [comment]
OK, this PR should be good for review now.  Glad we caught that broken link!

**Comment by jsf9k** [comment]
Can I get a review for this PR?  The unused imports and variables aren't a big deal, but it would be nice to get the broken link fix out into production.

**Review by dav3r — APPROVED** [review]
Looks good to me! 🇺🇸

**Pull request merged**
