### PR TITLE
Fix Travis CI

### PR DESCRIPTION
**Pull request by jsf9k**
I'm far from an expert on Ruby, Jekyll, etc., but I believe these changes are sufficient to make TravisCI successfully build the site.  It looks like TravisCI has been failing for the past six months, so this is definitely an improvement.

I also added code to run `html-proofer` on the site to ensure that all the images and hyperlinks actually point to a real source.  This seems to have turned up [one error](https://travis-ci.com/dhs-ncats/cyber.dhs.gov/builds/89597805#L592-L593).  See below (or the most recent failed build) for details.

### CODE REVIEW

**Comment by jsf9k** [comment]
Note that the build is failing because there is [a genuinely broken link](https://travis-ci.com/dhs-ncats/cyber.dhs.gov/builds/89597805#L592-L593).  Should this link instead point to https://home.dotgov.gov/management/preloading/?

**Comment by jsf9k** [comment]
I fixed the broken link, and the Travis CI build now passes.

**Review by dav3r — APPROVED** [review]
Strong work @jsf9k - way to add value!

**Review by h-m-f-t — APPROVED** [review]
LGTM

**Pull request merged**
